version: "3"
services:

    mongodb:
        image: mongo:3.2.12
        ports:
            - "27017:27017"

    postgresql:
        image: postgres:9.6.3
        ports:
            - "5432:5432"
        volumes:
            - ./docker_volumes/pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=jbl-dc
            - POSTGRES_PASSWORD=jbl-dc
            - POSTGRES_DB=jbl-dc
            - PGDATA=/var/lib/postgresql/data/pgdata

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
        ports:
            - "9200:9200"
        volumes:
            - ./docker_volumes/esdata:/usr/share/elasticsearch/data
        environment:
            - xpack.security.enabled=false
            - http.cors.enabled=true
            - http.cors.allow-origin=*
            - http.cors.allow-headers="X-Requested-With, Content-Type, Content-Length, Authorization"
    kibana:
        image: docker.elastic.co/kibana/kibana:5.4.3
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch
