version: "3"
services:

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
        ports:
            - "9200:9200"
        networks:
            - elk

    mongodb:
        image: mongo:3.2.12
        ports:
            - "27017:27017"
        networks:
            - elk

    kibana:
        image: docker.elastic.co/kibana/kibana:5.4.3
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch
        networks:
            - elk
networks:
  elk:
    driver: bridge